using System;
using System.IO;
using System.IO.Compression;
using System.Text;
using JobPortal.Shared.DTOs;
using JobPortal.Shared.Enums;
using JobPortal.Shared.Exceptions;
using JobPortal.Features.JobPosting;
using JobPortal.Features.Application;
using JobPortal.UI;
using Spectre.Console;

namespace JobPortal.Features.Reports;

internal static class ReportManager
{
    public static ReportDTO HiringReport(List<Application.Application1> applications, string adminId)
    {
        if (applications == null || applications.Count == 0)
            return EmptyReport(ReportType.HiringFunnel.ToString(), adminId, "No applications found.");

        int total = applications.Count;
        int pending = 0;
        int shortlisted = 0;
        int rejected = 0;
        int hired = 0;
        int interview = 0;

        foreach (Application1 application in applications)
        {
            if (application.Status == ApplicationStatus.PENDING)
            {
                pending++;
            }
            else if (application.Status == ApplicationStatus.SHORTLISTED)
            {
                shortlisted++;
            }
            else if (application.Status == ApplicationStatus.REJECTED)
            {
                rejected++;
            }
            else if (application.Status == ApplicationStatus.HIRED)
            {
                hired++;
            }
            else if (application.Status == ApplicationStatus.INTERVIEW_SCHEDULED)
            {
                interview++;
            }
        }
        double hireRate = total > 0 ? Math.Round((double)hired / total * 100, 1) : 0;
        var dto = new ReportDTO
        {
            ReportType = "Hiring Funnel",
            GeneratedBy = adminId,
            GeneratedAt = DateTime.Now,
            Data = new Dictionary<string, object>
            {
                ["TotalApplications"] = total,
                ["Pending"] = pending,
                ["Shortlisted"] = shortlisted,
                ["InterviewScheduled"] = interview,
                ["Rejected"] = rejected,
                ["Hired"] = hired,
                ["HireRate%"] = hireRate
            },
            Summary = $"Total: {total} | Shortlisted: {shortlisted} | Hired: {hired} | Rate: {hireRate}%"
        };
        return dto;
    }

    public static ReportDTO JobAnalytics(List<JobListing> listings, string adminId)
    {
        if (listings == null || listings.Count == 0)
            return EmptyReport(ReportType.JobAnalytics.ToString(), adminId, "No job listings found.");

        int total = listings.Count;
        int active = 0;
        int expired = 0;
        int closed = 0;
        int pending = 0;
        int rejected = 0;
        foreach (JobListing job in listings)
        {
            if (job.IsActive)
            {
                active++;
            }

            if (job.IsExpired())
            {
                expired++;
            }

            if (job.Status == JobStatus.CLOSED)
            {
                closed++;
            }

            if (job.Status == JobStatus.PENDING_APPROVAL)
            {
                pending++;
            }

            if (job.Status == JobStatus.REJECTED)
            {
                rejected++;
            }
        }

        var dto = new ReportDTO
        {
            ReportType = "Job Analytics",
            GeneratedBy = adminId,
            GeneratedAt = DateTime.Now,
            Data = new Dictionary<string, object>
            {
                ["TotalListings"] = total,
                ["Active"] = active,
                ["Expired"] = expired,
                ["Closed"] = closed,
                ["Pending"] = pending,
                ["Rejected"] = rejected
            },
            Summary = $"Total: {total} | Active: {active} | Expired: {expired} | Closed: {closed}"
        };
        return dto;
    }

    public static void ExportToCsv(ReportDTO report, string path)
    {
        try
        {
            var lines = new List<string>
            {
                $"Report Type,{report.ReportType}",
                $"Generated At,{report.GeneratedAt:yyyy-MM-dd HH:mm:ss}",
                $"Generated By,{report.GeneratedBy}",
                $"Summary,{report.Summary}",
                "",
                "Metric,Value"
            };
            foreach (var kv in report.Data)
                lines.Add($"{kv.Key},{kv.Value}");

            string dir = Path.GetDirectoryName(path) ?? ".";
            Directory.CreateDirectory(dir);
            File.WriteAllLines(path, lines);
        }
        catch (Exception ex)
        {
            throw new ReportGenerationException($"Failed to export report to CSV: {ex.Message}", ex);
        }
    }

    public static void ExportToTxt(ReportDTO report, string path)
    {
        try
        {
            var lines = new List<string>
            {
                $"==================================================",
                $"REPORT: {report.ReportType.ToUpper()}",
                $"==================================================",
                $"Generated At : {report.GeneratedAt:yyyy-MM-dd HH:mm:ss}",
                $"Generated By : {report.GeneratedBy}",
                $"Summary      : {report.Summary}",
                $"--------------------------------------------------",
                "METRICS:"
            };
            foreach (var kv in report.Data)
            {
                lines.Add($"  {kv.Key,-25}: {kv.Value}");
            }
            lines.Add($"==================================================");

            string dir = Path.GetDirectoryName(path) ?? ".";
            Directory.CreateDirectory(dir);
            File.WriteAllLines(path, lines);
        }
        catch (Exception ex)
        {
            throw new ReportGenerationException($"Failed to export report to TXT: {ex.Message}", ex);
        }
    }

    public static void ExportToDocx(ReportDTO report, string path)
    {
        try
        {
            string dir = Path.GetDirectoryName(path) ?? ".";
            Directory.CreateDirectory(dir);

            if (File.Exists(path)) File.Delete(path);

            using (var fileStream = new FileStream(path, FileMode.Create))
            using (var archive = new ZipArchive(fileStream, ZipArchiveMode.Create))
            {
                var contentTypesEntry = archive.CreateEntry("[Content_Types].xml");
                using (var writer = new StreamWriter(contentTypesEntry.Open(), Encoding.UTF8))
                {
                    writer.Write(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Types xmlns=""http://schemas.openxmlformats.org/package/2006/content-types"">
  <Default Extension=""rels"" ContentType=""application/vnd.openxmlformats-package.relationships+xml""/>
  <Default Extension=""xml"" ContentType=""application/xml""/>
  <Override PartName=""/word/document.xml"" ContentType=""application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml""/>
</Types>");
                }

                var relsEntry = archive.CreateEntry("_rels/.rels");
                using (var writer = new StreamWriter(relsEntry.Open(), Encoding.UTF8))
                {
                    writer.Write(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Relationships xmlns=""http://schemas.openxmlformats.org/relationships"">
  <Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"" Target=""word/document.xml""/>
</Relationships>");
                }

                var docEntry = archive.CreateEntry("word/document.xml");
                using (var writer = new StreamWriter(docEntry.Open(), Encoding.UTF8))
                {
                    var sb = new StringBuilder();
                    sb.Append(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>");
                    sb.Append(@"<w:document xmlns:w=""http://schemas.openxmlformats.org/wordprocessingml/2006/main"">");
                    sb.Append(@"<w:body>");

                    sb.Append("<w:p><w:r><w:rPr><w:sz w:val=\"36\"/><w:b/></w:rPr><w:t>");
                    sb.Append(System.Security.SecurityElement.Escape($"Report: {report.ReportType}"));
                    sb.Append("</w:t></w:r></w:p>");

                    sb.Append($"<w:p><w:r><w:t>Generated At: {report.GeneratedAt:yyyy-MM-dd HH:mm:ss}</w:t></w:r></w:p>");
                    sb.Append($"<w:p><w:r><w:t>Generated By: {report.GeneratedBy}</w:t></w:r></w:p>");
                    sb.Append("<w:p><w:r><w:rPr><w:i/></w:rPr><w:t>");
                    sb.Append(System.Security.SecurityElement.Escape($"Summary: {report.Summary}"));
                    sb.Append("</w:t></w:r></w:p>");

                    sb.Append("<w:p><w:r><w:t>--------------------------------------------------</w:t></w:r></w:p>");

                    foreach (var kv in report.Data)
                    {
                        sb.Append("<w:p>");
                        sb.Append("<w:r><w:rPr><w:b/></w:rPr><w:t>");
                        sb.Append(System.Security.SecurityElement.Escape($"{kv.Key}: "));
                        sb.Append("</w:t></w:r>");
                        sb.Append("<w:r><w:t>");
                        sb.Append(System.Security.SecurityElement.Escape($"{kv.Value.ToString() ?? ""}"));
                        sb.Append("</w:t></w:r>");
                        sb.Append("</w:p>");
                    }

                    sb.Append(@"</w:body>");
                    sb.Append(@"</w:document>");
                    writer.Write(sb.ToString());
                }
            }
        }
        catch (Exception ex)
        {
            throw new ReportGenerationException($"Failed to export report to DOCX: {ex.Message}", ex);
        }
    }

    public static void ExportToPdf(ReportDTO report, string path)
    {
        try
        {
            string dir = Path.GetDirectoryName(path) ?? ".";
            Directory.CreateDirectory(dir);

            var contentBuilder = new StringBuilder();
            contentBuilder.AppendLine("BT");
            contentBuilder.AppendLine("/F1 18 Tf");
            contentBuilder.AppendLine("50 800 Td");
            contentBuilder.AppendLine($"(Report: {EscapePdfString(report.ReportType)}) Tj");
            contentBuilder.AppendLine("T*");
            contentBuilder.AppendLine("/F1 12 Tf");
            contentBuilder.AppendLine($"(Generated At: {report.GeneratedAt:yyyy-MM-dd HH:mm:ss}) Tj");
            contentBuilder.AppendLine("T*");
            contentBuilder.AppendLine($"(Generated By: {EscapePdfString(report.GeneratedBy)}) Tj");
            contentBuilder.AppendLine("T*");
            contentBuilder.AppendLine($"(Summary: {EscapePdfString(report.Summary)}) Tj");
            contentBuilder.AppendLine("T*");
            contentBuilder.AppendLine("0 -15 Td");
            contentBuilder.AppendLine("(--------------------------------------------------) Tj");
            contentBuilder.AppendLine("T*");

            foreach (var kv in report.Data)
            {
                contentBuilder.AppendLine($"({EscapePdfString(kv.Key)}: {EscapePdfString(kv.Value.ToString() ?? "")}) Tj");
                contentBuilder.AppendLine("T*");
            }
            contentBuilder.AppendLine("ET");

            string textStream = contentBuilder.ToString();
            byte[] streamBytes = Encoding.UTF8.GetBytes(textStream);
            int streamLength = streamBytes.Length;

            using (var fs = new FileStream(path, FileMode.Create))
            using (var writer = new StreamWriter(fs, Encoding.ASCII))
            {
                var offsets = new List<long>();

                writer.Write("%PDF-1.4\n");
                writer.Flush();

                offsets.Add(fs.Position);
                writer.Write("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
                writer.Flush();

                offsets.Add(fs.Position);
                writer.Write("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
                writer.Flush();

                offsets.Add(fs.Position);
                writer.Write("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n");
                writer.Flush();

                offsets.Add(fs.Position);
                writer.Write($"4 0 obj\n<< /Length {streamLength} >>\nstream\n");
                writer.Flush();

                fs.Write(streamBytes, 0, streamBytes.Length);
                fs.Flush();

                writer.Write("\nendstream\nendobj\n");
                writer.Flush();

                offsets.Add(fs.Position);
                writer.Write("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");
                writer.Flush();

                long xrefPos = fs.Position;
                writer.Write("xref\n");
                writer.Write($"0 {offsets.Count + 1}\n");
                writer.Write("0000000000 65535 f \n");
                foreach (long offset in offsets)
                {
                    writer.Write($"{offset:D10} 00000 n \n");
                }
                writer.Flush();

                writer.Write("trailer\n");
                writer.Write($"<< /Size {offsets.Count + 1} /Root 1 0 R >>\n");
                writer.Write("startxref\n");
                writer.Write($"{xrefPos}\n");
                writer.Write("%%EOF\n");
                writer.Flush();
            }
        }
        catch (Exception ex)
        {
            throw new ReportGenerationException($"Failed to export report to PDF: {ex.Message}", ex);
        }
    }

    private static string EscapePdfString(string s)
    {
        if (string.IsNullOrEmpty(s)) return "";
        return s.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
    }

    public static void DisplayReport(ReportDTO report)
    {
        JobPortal.UI.ConsoleHelper.PrintHeader($"Report: {report.ReportType}");
        Console.WriteLine($"  Generated : {report.GeneratedAt:dd MMM yyyy HH:mm}");
        Console.WriteLine($"  Summary   : {report.Summary}");
        JobPortal.UI.ConsoleHelper.PrintSeparator();
        foreach (var kv in report.Data)
            Console.WriteLine($"  {kv.Key,-25}: {kv.Value}");
    }

    public static void RenderPreview(ReportDTO report)
    {
        var table = new Table()
            .Border(TableBorder.Rounded)
            .BorderStyle(Style.Parse(UITheme.Primary))
            .Title($"[bold {UITheme.Primary}]Report Preview: {report.ReportType}[/]")
            .AddColumn($"[bold {UITheme.Warning}]Metric[/]")
            .AddColumn($"[bold {UITheme.Warning}]Value[/]");

        table.AddRow("Report Type", report.ReportType);
        table.AddRow("Generated By", report.GeneratedBy);
        table.AddRow("Generated At", report.GeneratedAt.ToString("g"));
        table.AddRow("Summary", report.Summary);

        table.AddEmptyRow();
        table.AddRow("[bold white]Metrics[/]", "");

        foreach (var kv in report.Data)
        {
            table.AddRow(kv.Key, kv.Value.ToString() ?? "");
        }

        AnsiConsole.Write(table);
    }

    private static ReportDTO EmptyReport(string type, string adminId, string message) =>
        new ReportDTO
        {
            ReportType = type,
            GeneratedBy = adminId,
            GeneratedAt = DateTime.Now,
            Data = new Dictionary<string, object>(),
            Summary = message
        };
}